GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/6139302179f6a92eedf0e815

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Esther Asante",
    "subscribedToChannel": "Joma Tech"
}

###

DELETE http://localhost:3000/subscribers/6139302179f6a92eedf0e815

###

PATCH http://localhost:3000/subscribers/6139304679f6a92eedf0e817
Content-Type: application/json

{
    "name": "Ibrahim"
}